/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Child: typeof import('./src/components/child.vue')['default']
    ElTree: typeof import('element-plus/es/el-tree')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
  }
}
